# Generated by Django 4.1.1 on 2022-09-28 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='emailid',
            new_name='email',
        ),
    ]
