# Generated by Django 4.1.1 on 2022-09-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_emailid_account_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phonenumber',
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
